# Module settings that users cannot modify.
resources:
  automatic:
    # Links for automatically downloaded files
    co2stop: https://setis.ec.europa.eu/document/download/786a884f-0b33-4789-b744-28004b16bd1a_en?filename=co2jrc_openformats.zip
