# A minimal example of how to configure this module
crs:
  geographic: "epsg:4326"
  projected: "epsg:3035"

imputation:
  bounds_mtco2:
    co2stop_polygons:
      # Constrain rows within the CO2Stop database
      lower: 10
      upper: 300000
    aggregated_polygons:
      # Constrain rows within your requested regions
      lower: 50
      upper: 5000000  # TtCO2 -> essentially no upper limit
  filter:
    surface_issues: True
    subsurface_issues: True
    artificial_polygons: True
