# A minimal example of how to configure this module
crs:
  geographic: "epsg:4326"
  projected: "epsg:3035"

imputation:
  filter:
    surface_issues: False
    subsurface_issues: False
    artificial_polygons: True
  datasets: ["traps", "storage_units"]
  groups: ["aquifer", "oil", "gas"]
