# A minimal example of how to configure this module
crs:
  geographic: "epsg:4326"
  projected: "epsg:3035"

imputation:
  bounds_mtco2:
    storage_units:
      lower: 20
      upper: 300000
    traps:
      lower: 20
      upper: 300000
  filter:
    surface_issues: True
    subsurface_issues: True
    artificial_polygons: True
